# Generated by Django 3.2.9 on 2022-01-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
